# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', '临时文章'), ('comment', '临时评论')], max_length=20, verbose_name='类型')),
                ('content', models.TextField(verbose_name='信息内容')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdatas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
