# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='文章分类网址', max_length=10, unique=True, verbose_name='分类网址')),
                ('name', models.CharField(help_text='文章分类名称', max_length=40, unique=True, verbose_name='分类名称')),
                ('level', models.IntegerField(blank=True, default=1, help_text='目录级别', verbose_name='目录级别')),
                ('parent', models.ForeignKey(blank=True, help_text='父级目录', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='父级目录')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类列表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='评论内容', max_length=512, verbose_name='评论内容')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='评论者IP地址', null=True, verbose_name='用户IP')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='评论更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='删除评论', verbose_name='删除评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论列表',
                'ordering': ('-time_added',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='图片名称', max_length=100, verbose_name='图片名')),
                ('url', models.ImageField(help_text='图片路径', storage=utils.storage.ImageStorage(), upload_to='img/article/%Y/%m', verbose_name='图片')),
                ('time_added', models.DateTimeField(auto_now_add=True, help_text='上传时间', verbose_name='上传时间')),
                ('deleted', models.BooleanField(default=False, help_text='删除图片', verbose_name='删除')),
                ('user', models.ForeignKey(blank=True, help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片列表',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章标题', max_length=128, verbose_name='标题')),
                ('content', models.TextField(help_text='文章内容', verbose_name='文章内容')),
                ('time_added', models.DateTimeField(auto_now_add=True, help_text='文章创建时间', verbose_name='创建时间')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text='更新文章时间', verbose_name='更新时间')),
                ('status', models.CharField(blank=True, choices=[('published', '发布'), ('draft', '草稿')], default='published', help_text='文章状态(draft/published)', max_length=10, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, help_text='文章置顶', verbose_name='置顶')),
                ('is_good', models.BooleanField(default=False, help_text='精华文章', verbose_name='精华')),
                ('deleted', models.BooleanField(default=False, help_text='文章已删除', verbose_name='已删除')),
                ('visit_count', models.IntegerField(blank=True, default=0, help_text='文章阅读数', verbose_name='阅读量')),
                ('reply_count', models.IntegerField(blank=True, default=0, help_text='文章回复数', verbose_name='回复数')),
                ('author', models.ForeignKey(help_text='文章作者', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(help_text='文章分类', on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章列表',
                'ordering': ('-time_added',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='标签网址', max_length=15, verbose_name='网址')),
                ('name', models.CharField(help_text='标签名称', max_length=30, verbose_name='标签名')),
                ('is_hot', models.BooleanField(default=False, help_text='是否是热门标签', verbose_name='热门')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='文章标签', related_name='articles', to='article.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='评论文章', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Post', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
